[package]
name = "Pyroclastic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ash = "0.38.0"
vulcano = "0.1.1"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
vulkano-win = "0.34.0"
winit = "0.30.11"
